@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "Main#main(String[])",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "Main",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1199917228 { 
   	label=adminusuarios
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_511862017 { 
   	label=GestorUsuarios
	labeljust=l
	fillcolor=white
	style=filled
   
   GestorUsuarios1199917228XXXautenticarUsuario2013066710[
	label="+ autenticarUsuario()"
	style=filled
	fillcolor=white
	tooltip="GestorUsuarios

null"
	fontcolor=darkgreen
];

GestorUsuarios1199917228XXXcargarUsuariosDesdeCSV1808118735[
	label="+ cargarUsuariosDesdeCSV()"
	style=filled
	fillcolor=white
	tooltip="GestorUsuarios

null"
	fontcolor=darkgreen
];

GestorUsuarios1199917228XXXcrearUsuario18766814[
	label="+ crearUsuario()"
	style=filled
	fillcolor=white
	tooltip="GestorUsuarios

null"
	fontcolor=darkgreen
];

GestorUsuarios1199917228XXXobtenerNuevoIdUsuario0[
	label="+ obtenerNuevoIdUsuario()"
	style=filled
	fillcolor=white
	tooltip="GestorUsuarios

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_193335905 { 
   	label=adminproyectos
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_603928029 { 
   	label=GestorProyectos
	labeljust=l
	fillcolor=white
	style=filled
   
   GestorProyectos193335905XXXbuscarProyectoPorId104431[
	label="+ buscarProyectoPorId()"
	style=filled
	fillcolor=white
	tooltip="GestorProyectos

null"
	fontcolor=darkgreen
];

GestorProyectos193335905XXXcargarProyectosDesdeCSV1808118735[
	label="+ cargarProyectosDesdeCSV()"
	style=filled
	fillcolor=white
	tooltip="GestorProyectos

null"
	fontcolor=darkgreen
];

GestorProyectos193335905XXXcrearProyecto0[
	label="+ crearProyecto()"
	style=filled
	fillcolor=white
	tooltip="GestorProyectos

null"
	fontcolor=darkgreen
];

GestorProyectos193335905XXXeliminarProyecto104431[
	label="+ eliminarProyecto()"
	style=filled
	fillcolor=white
	tooltip="GestorProyectos

null"
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_2390489 { 
   	label=Main
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1706522830 { 
   	label=Main
	labeljust=l
	fillcolor=white
	style=filled
   
   Main2390489XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="Main

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 

subgraph cluster_427039518 { 
   	label=reportes
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1487095449 { 
   	label=GeneradorReportes
	labeljust=l
	fillcolor=white
	style=filled
   
   GeneradorReportes427039518XXXgenerarReporteResumen1794054715[
	label="+ generarReporteResumen()"
	style=filled
	fillcolor=white
	tooltip="GeneradorReportes

null"
	fontcolor=darkgreen
];
} 
} 

'edges    
GestorProyectos193335905XXXeliminarProyecto104431 -> GestorProyectos193335905XXXbuscarProyectoPorId104431;
Main2390489XXXmain1859653459 -> GeneradorReportes427039518XXXgenerarReporteResumen1794054715;
Main2390489XXXmain1859653459 -> GestorProyectos193335905XXXcargarProyectosDesdeCSV1808118735;
Main2390489XXXmain1859653459 -> GestorProyectos193335905XXXcrearProyecto0;
Main2390489XXXmain1859653459 -> GestorProyectos193335905XXXeliminarProyecto104431;
Main2390489XXXmain1859653459 -> GestorUsuarios1199917228XXXautenticarUsuario2013066710;
Main2390489XXXmain1859653459 -> GestorUsuarios1199917228XXXcargarUsuariosDesdeCSV1808118735;
Main2390489XXXmain1859653459 -> GestorUsuarios1199917228XXXcrearUsuario18766814;
Main2390489XXXmain1859653459 -> GestorUsuarios1199917228XXXobtenerNuevoIdUsuario0;
    
}
@enduml